### ISSUE TITLE
Invalid block signature

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi#101]
I keep receiving the following error while running the testnet:

019-04-11T08:58:10Z ERROR: CheckBlock(): block signature invalid

it has appeared several times.

May be related, I also receive this one:

2019-04-11T08:58:10Z ERROR: ProcessNewBlock: AcceptBlock FAILED (bad-block-signature (code 16))

**Comment by durkmurder** [comment]
Not an issue, this happens when receiving compact block, which we don't actually handle.
