### ISSUE TITLE
Testnet (mobile & desktop) - 1.0.4 & 1.0.7 - fundmasternode output : port issues

### ISSUE THREAD

**Issue by gingfinger** [DiviProject/Divi#108]
The output of fundmasternode in 1.0.4 & 1.0.7 testnet gives the resulting config a port of 51474 like in this example:

mycopper 134.209.192.92:51474 cQ6CwkD56dSJe2qGxnEBUvMpjAwwZu2vMV86ax8zEVs7TrPiwQYe a3ee1e47c3ca0e9a25838809d6a73a1345c1169b2b29f476adb45d4a48fa64d9 1

However, the remote host will not activate with this as the port. If the port is changed in the config line to 51473, then the Masternode will start remotely just fine like so:

mycopper 134.209.192.92:51473 cQ6CwkD56dSJe2qGxnEBUvMpjAwwZu2vMV86ax8zEVs7TrPiwQYe a3ee1e47c3ca0e9a25838809d6a73a1345c1169b2b29f476adb45d4a48fa64d9 1

So either the output of fundmasternode needs to change the port it gives, or something else is needing changed that means the masternode will accept a start command with 51474 as the port. It is easy enough to work around this when using the desktop app or cli as I can modify the config line myself and get the masternode to run. However, this issue has carried over into the mobile builds, so it isn't actually possible for the masternode to be started as I can't manually intervene on the automated process and do the changes.

**Comment by 99darwin** [comment]
I experienced the same behavior. The workaround is to change the config line to include port 51473. Will get this worked out in the next build.

**Comment by galpHub** [comment]
Fixed in #196
