### ISSUE TITLE
Mobile Masternode Deployment: Node stuck mid deployment

### ISSUE THREAD

**Issue by gingfinger** [DiviProject/Divi#109]
I decided to try and test the limits of deployment and see if it would allow me to deploy multiple nodes at once by going back and launching another like so:
![user-images.githubusercontent.com&#x2F;39313339&#x2F;57952468-3f847500-78e5-11e9-9a65-15c2d87aa64b.png](https://)

It seemed to accept this practice and start setting up the nodes. Although this is not a normal thing to be doing. Several hours later I went back to check on how the multi-deployment went and found one of them stuck at 75% like so:
![user-images.githubusercontent.com&#x2F;39313339&#x2F;57952486-4dd29100-78e5-11e9-9b65-e280efdfb0eb.png](https://)

I was able to dismantle the other 2 and refund the collateral, but the one at 75% is completely stuck now and cant be stopped deploying or refunded. It is just permanently stuck at 75%

**Comment by galpHub** [comment]
This issue will be resolved in the upcoming release. Closing this PR for now.
