### ISSUE TITLE
Suggestion/Request 1.0.8 : getinfo

### ISSUE THREAD

**Issue by gingfinger** [DiviProject/Divi#110]
Is it possible to have the "getinfo" command back. As a high level overview tool it was great.

Could instantly see balance, peers count, block count, staking status, errors, coins supply, difficulty and key pool size. 

That level of overview is sorely missed in the current builds and each one of those bits of info has to now be independently sourced via various commands

**Comment by durkmurder** [comment]
It was intentionally done that way, to save resources when calling `getinfo` usually you need only a part of it, use: `getstakingstatus`, `getblockchaininfo`, `getwalletinfo`, `getpeerinfo`

**Comment by gingfinger** [comment]
Thanks for the clarification
