### ISSUE TITLE
1.0.8 testnet : mnsync

### ISSUE THREAD

**Issue by gingfinger** [DiviProject/Divi#111]
Unable to achieve MNSYC status to be true 

I have tried to mnsync reset and restart the daemon several times. both methods have not been successful in  achieving a full MNSYNC

**Comment by durkmurder** [comment]
How many peers you have? To sync masternode network you need at least 3 peers.

**Comment by gingfinger** [comment]
I currently have 5 peers:
"validtime": true,
  "haveconnections": true,
  "walletunlocked": true,
  "mintablecoins": true,
  "enoughcoins": true,
  "mnsync": false,
  "staking status": false

mnsync status:

"IsBlockchainSynced": true,
  "lastMasternodeList": 0,
  "lastMasternodeWinner": 1558261427,
  "lastFailure": 1558260950,
  "nCountFailures": 0,
  "sumMasternodeList": 0,
  "sumMasternodeWinner": 0,
  "countMasternodeList": 0,
  "countMasternodeWinner": 0,
  "RequestedMasternodeAssets": 2,
  "RequestedMasternodeAttempt": 1

**Comment by gingfinger** [comment]
mnsyc has now went good once 3 masternodes minimum came online , there were previously only 2 at the time. Issue seems self resolving now
