### ISSUE TITLE
Gitian building is a grueling experience

### ISSUE THREAD

**Issue by galpHub** [DiviProject/Divi#121]
Don't believe me, try it.

This is the ideal situation where you want to have a docker container with the relevant components prebuilt so as to only require pointing it to a specific repo (similar to the project on https://github.com/kleetus/docker-based-gitian-builder). Would save a lot of time as well as making the process reproducible and easier for on-boarding personnel.

**Comment by ChrisCates** [comment]
@galpHub, definitely!

We should have everything precompiled and that way all you have to do is a simple pull and not have to compile within the Docker container.
