### ISSUE TITLE
Testnet not sync. Version 1.0.4.0

### ISSUE THREAD

**Issue by txsdev** [DiviProject/Divi#130]
# Environment
MacOs 

## divi.conf

```
testnet=1
rpcuser=divi
rpcpassword=divipassword
rpcallowip=127.0.0.1
rpcconnect=127.0.0.1

server=1
daemon=1
```

## Start Node method 
> divid

## Divi cli
> divi-cli getblockchaininfo

```
{
"chain" : "test",
"blocks" : 0,
"headers" : 0,
"bestblockhash" : "00000e258596876664989374c7ee36445cf5f4f80889af415cc32478214394ea",
"difficulty" : 0.00024414,
"verificationprogress" : 0.00000951,
"chainwork" : "0000000000000000000000000000000000000000000000000000000000100010"
}
```

How to solve this ? Thx very mush

**Comment by ChrisCates** [comment]
Hi Tian!

We are working on a resetting the testnet.
We will give updates when it is ready!

Thank you for your patience. 😊
Sorry for the delays.
-- 
*Chris Cates:**"Every decision in your life can be determined in O(log*
*₂(n))"*
*| chriscates.ca <http://chriscates.ca>* | hello@chriscates.ca |
github.com/ChrisCates |
