### ISSUE TITLE
How to generate address?

### ISSUE THREAD

**Issue by txsdev** [DiviProject/Divi#131]
How i generate `address` from private_key?

## I understand steps
`private_key -> public_key -> pubkey_hash -> base58.encode(version + pubkey_hash)`

What is mean about `version`?  I not found some doc about `address`

Thanks.

**Comment by 7h3v01c3** [comment]
from command line you generate an address with 

./divi-cli getnewaddress

**Comment by txsdev** [comment]
> from command line you generate an address with
> 
> ./divi-cli getnewaddress

Thx. but i want to generate address with offline not divi-node
