### ISSUE TITLE
listunspent is null

### ISSUE THREAD

**Issue by txsdev** [DiviProject/Divi#132]
## Environment
MacOS 

## divi.conf
```
rpcuser=divi
rpcpassword=divipassword
#rpcport=51473
rpcallowip=0.0.0.0/0

server=1
daemon=1
```  

## start 
> divid  

## get listunspent 
1. divi-cli importaddress "address" "normal" true 
2. divi-cli -rpcuser=divi -rpcpassword=divipassword listunspent 0 9999999 "[\"address\"]"

Result: 
[]

Explain： target address have balance

Thanks，How to resolve it?

**Comment by txsdev** [comment]
## divi-cli getinfo 
```json
{
    "version" : "1.0.4.0",
    "protocolversion" : 70915,
    "walletversion" : 120200,
    "balance" : 0.00000000,
    "zerocoinbalance" : 0.00000000,
    "blocks" : 598398,
    "timeoffset" : -1,
    "connections" : 16,
    "proxy" : "",
    "difficulty" : 5837.96293251,
    "testnet" : false,
    "moneysupply" : 1363603744.87528443,
    "keypoololdest" : 1574221964,
    "keypoolsize" : 1999,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00010000,
    "staking status" : "Staking Not Active",
    "errors" : ""
}
```

**Comment by gingfinger** [comment]
If you import an address, it only becomes a watch address. It isn't your address until you import the private key:

You can check if the address is yours with: divi-cli validateaddress diviaddress

If the ismine=false then you need to import its key and then rescan the chain

I assume that is what you are trying to achieve?

**Comment by txsdev** [comment]
> divi-cli validateaddress

Thx. I have fixed and what we need is `watch address`. 
1. stop node
2. add `addressindex=1` to `divi.conf`
3. remove `blocks` and `chainstate` 
4. start node
