### ISSUE TITLE
Build fails on Debian Buster with Boost asio SSL error

### ISSUE THREAD

**Issue by domob1812** [DiviProject/Divi#158]
Building Divi from source fails on Debian buster, presumably related to the Boost version (1.67 by default).  The error I get is [build.log](https://github.com/DiviProject/Divi/files/4111915/build.log).

It seems that `basic_socket_acceptor` was changed to only have one template argument some time between version [1.65](https://www.boost.org/doc/libs/1_65_1/doc/html/boost_asio/reference/basic_socket_acceptor.html) and [1.67](https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/basic_socket_acceptor.html).

I think upstream Bitcoin removed RPC over SSL a long time ago, so maybe doing that is the simplest to fix this.

**Comment by galpHub** [comment]
Hey Daniel,
I'm looking into this now. Is this building master0 that you're seeing the problem with?

**Comment by domob1812** [comment]
Originally I wanted to build `v1.0.7`.  But I tried now with `master0` as well (commit 1b9339fba96f28d75674aa59d632806042a5303f), and it gives the same result.

Thanks for looking into this!  Perhaps just removing SSL support for RPC is the easiest thing to do, as was done by Bitcoin long ago.  SSL isn't really useful for RPC anyway - typically RPC would be local only; and if you really want to do something fancy and expose the RPC port, then you can put your own VPN or reverse TLS proxy in front for security.

**Comment by galpHub** [comment]
> Originally I wanted to build `v1.0.7`. But I tried now with `master0` as well (commit [1b9339f](https://github.com/DiviProject/Divi/commit/1b9339fba96f28d75674aa59d632806042a5303f)), and it gives the same result.
> 
> Thanks for looking into this! Perhaps just removing SSL support for RPC is the easiest thing to do, as was done by Bitcoin long ago. SSL isn't really useful for RPC anyway - typically RPC would be local only; and if you really want to do something fancy and expose the RPC port, then you can put your own VPN or reverse TLS proxy in front for security.

I see. Yeah, I tried a few things to get it working (using version number-based defines and such to overcome the difference in template parameters) but lots of ssl & boost related errors. Currently tied up but haven't forgotten about this. 

Regarding the possibility of removing ssl support, do you have a link to the btc changes per chance? If you could drop that here that'd be great

**Comment by domob1812** [comment]
Sure, I think it was [Bitcoin PR 5677](https://github.com/bitcoin/bitcoin/pull/5677).  However, that is a large refactoring, so I'm not sure if that can help you here directly.
