### ISSUE TITLE
Update merge process

### ISSUE THREAD

**Issue by ChrisCates** [DiviProject/Divi#169]
### Description

In order to make sure new diffs in the codebase are appropriate. We need to update how merges happen in each pull request. I've actually created a guide on this a while back, and it feels very appropriate to implement [everything mentioned in it.](https://www.dropbox.com/s/gottbv0teycp53m/Continuous%20Delivery%20in%20Git.pdf?dl=0)

1. We need to create a `development` and `staging` branch. This can be done by doing:

```bash
git checkout master0
git checkout -b development
git push origin development

git checkout master0
git checkout -b staging
git push origin staging
```

2. We would need to ensure the `master` branch is protected.

**Below are some reference screenshots to update the master branch**

First go to branches in settings:

<img width="1040" alt="Screen Shot 2020-02-09 at 1 39 30 PM" src="https://user-images.githubusercontent.com/1561091/74107786-a582ed80-4b41-11ea-9d4c-281bd1c561ed.png">

Then go to branch protection rules:

<img width="1009" alt="Screen Shot 2020-02-09 at 1 43 35 PM" src="https://user-images.githubusercontent.com/1561091/74107862-4e314d00-4b42-11ea-9fc4-0eb679835d71.png">

Make sure to update with *require pull request reviews* and *status checks to pass*.

3. We would need to update the workflow to have **staging** deployments first. This would mean that we need to ensure that a few staging nodes work properly in the network and can receive peers and not hard fork the chain.

**Comment by 99darwin** [comment]
To expand upon item 1, and in relation to issue #170 I would propose a `segwit-staging` branch.

Further, let's set up a 'StageNet' that mimics the current main net 1:1 (minus the obvious, to prevent forking). @galpHub has some thoughts on how this can be implemented. The reasoning for this is to deploy daemon updates to a network that will react similarly to the main network prior to a push to production.

**Comment by 99darwin** [comment]
Also, as @galpHub mentioned on today's call, we should determine and implement a new unit testing framework to round out the new workflow prior to the implementation of #170

**Comment by ChrisCates** [comment]
@99darwin, I think we're all in a consensus with **[GoogleTest](https://github.com/google/googletest)**. We should just focus on phasing out existing Boost test cases and update it in a rolling fashion to GoogleTest Framework.

**Comment by ChrisCates** [comment]
@99darwin, also can we update `master0` to `master`?

**Comment by ChrisCates** [comment]
Also, ended up changing master0 to master.
