### ISSUE TITLE
Version number not updated on Release 1.0.8

### ISSUE THREAD

**Issue by pascallapointe** [DiviProject/Divi#176]
### Description

When building source from release v1.0.8, client version still displayed as 1.0.7.
The version number as been committed on February 29 on the master branch.
Last commit under tag v1.0.8 is dated from February 27.

Building from last release won't connect to current network.

### Environment

Ubuntu:Bionic inside docker container running on Ubuntu 19.10 on Ubuntu 19.10 (GNU/Linux 5.3.0-1017-raspi2 aarch64)

**Comment by ChrisCates** [comment]
Hi @pascallapointe, can you confirm which branch you're pulling from?

**Comment by pascallapointe** [comment]
Sure,
I'm pulling from master and then, checkout tag v1.0.8.

```
git clone git@github.com:DiviProject/Divi.git .
git checkout v1.0.8
```

My usage/understanding of git & tag could be wrong though.
I've also build divi core from the master branch and everything seems fine so far. (version 1.0.8 displayed with divi-cli getinfo command)

**Comment by galpHub** [comment]
Hey @pascallapointe,

Thank you for pointing this out. I've tried to do this myself and as a matter of fact it finds the tag on the *wrong* branch (the development branch in this case). It's a mistagging. We will be remedying this in the near team.

**Comment by 7h3v01c3** [comment]
We are on public version 2.5.1 closing
