### ISSUE TITLE
Staking is turned off after unlocking wallet

### ISSUE THREAD

**Issue by MarcelSinteur** [DiviProject/Divi#199]
### Description

If the wallet is unlocked for stacking and during that time you want to send Divi to any address, you have to unlock your wallet completely. However, because there is a timer for unlocking your wallet (for example 5 minutes), after those 5 minutes, the wallet will lock again and stop staking. You have to manually unlock your wallet for staking again.

I would say that if you unlock your wallet for 5 minutes for doing a transaction, after those 5 minutes it should go back to 'Unlocked for staking only'. (If that's what you were doing before, obviously)

### Environment

Windows 10

**Comment by galpHub** [comment]
Hey @MarcelSinteur,
Sorry bout the incredibly late reply. We will take a look at this. Sounds like a feature that we can consider adding in a future core update. Thank you for suggesting it!
