### ISSUE TITLE
Amounts are not the same in Wallet and on Blockchain Explorer how can that be? 

### ISSUE THREAD

**Issue by Bubbu17** [DiviProject/Divi#219]
Amounts are not the same in Wallet and on Blockchain how can that be?

[//]: # (Describe the issue you are experiencing. Can be a brief description of what went wrong.)
Amounts are not the same in Wallet and on Blockchain how can that be?
https://chainz.cryptoid.info/divi/address.dws?DUAc2YJfQKmC7CGpE2rWkoD6MTKEg4VdKE.htm
Amount In Blockchain Explorer
![image](https://user-images.githubusercontent.com/62136070/127720378-fa3e1369-f9b7-4ac4-8229-6d552f2c9100.png)
Amount In Wallet
![image](https://user-images.githubusercontent.com/62136070/127720411-f53c10de-7818-4ef2-9093-5ed3130b8c50.png)
Which one is Right?

[//]: # (The environment you experienced the issue. ie: Ubuntu 18.04. If possible, provide versions of the packages you used if they are different to a standard build.)

Client: 1.8.0 
Daemon: DIVI Core: 2.0.1.0 
Wallet status: Unlocked, staking only

[//]: # (Any other notes in regards to the issue.)

**Comment by 7h3v01c3** [comment]
Your Divi Desktop Application is empowered with a wallet that is called hierarchical deterministic.

This means your Divi Desktop Application manages many addresses for you in one application.|

You are looking at only one of the many addresses you have (roughly 2000). A block explorer isn't capable of seeing your wallet, but it can show you your history on a single address. You would need to look at every address on the block explorer and then total it up if you wanted to see your entire available balance. Or easily ope Divi Desktop Application, and it will do it for you.
