### ISSUE TITLE
How can i update my DIVI Core?

### ISSUE THREAD

**Issue by Bubbu17** [DiviProject/Divi#221]
### Description

i have no cloue on how to update my divi Wallet to Core 2.5.1

### Environment

Windows 10 and divi Desktop 1.8.0 with 2.0.1.0 Divi core Deamon 

### Notes

Please help

**Comment by 7h3v01c3** [comment]
This is off-topic, for the Divi Core channel, you need Desktop Support.

If you do have questions about your Desktop Version please visit support.diviproject.org

We will happily answer your questions.
