### ISSUE TITLE
Chain hard fork on block 1952950

### ISSUE THREAD

**Issue by APshenkin** [DiviProject/Divi#233]
### Description

Our nodes come to chain fork at block 1952950

Some of nodes get d41ae4cca3ff604d2191ece6580a39f428eef86ef650b90637581b1fb6efbc35
Some of nodes get 0317fa6d21684f32afb0b444c50804fe8863d05d4927f024e3d0b14d0ca2be4a

Seems deep chain reorganization happens. Maybe there were 51% attack or something similar

### Environment

Ubuntu 20.04
DIVI Core: 2.5.1.0

### Notes

Currently one chain max height is 1955111
Other one has 1955180

Can you advice what nodes maintainers should do and what chain is correct

**Comment by galpHub** [comment]
Hello there!

`Explanation`: The correct chain is the one with highest difficulty. Roughly on the order of 20k (as opposed to ~1k). The correct chain at that block height has blockhash: 0317fa6d21684f32afb0b444c50804fe8863d05d4927f024e3d0b14d0ca2be4a. This is not the result of a 51% attack, but rather a sporadic issue that can occur depending on connectivity. It'll will be resolved in an upcoming release.

`Advice`: Resync the nodes on the incorrect chain and add peers known to be on the correct chain, by using the -resync=1 flag at startup (only needed once to resync) it will redownload the chain and reverify everything.

Best of luck!
