### ISSUE TITLE
Setting interface confusing

### ISSUE THREAD

**Issue by hirscr** [DiviProject/Divi#91]
I’m going through the settings, love how they are laid out. I don’t love how similar things are. Under maintenance, with no explanation, I would have no idea what those buttons do or why I might press them. I wouldn’t even go tooptip with these. I would have has text box below that changes as you hover over the buttons and describes what those buttons do and why or when you might press them.

Same for security page in settings. Backup from seed and recover from seed don’t sound like different things. Also the buttons are oddly spaced.

**Comment by 99darwin** [comment]
Reopened in the proper repository
