### ISSUE TITLE
Block explorer and wallet need to display "from address"

### ISSUE THREAD

**Issue by hirscr** [DiviProject/Divi#93]
Not sure what else to include other than the title. The from address needs to be able to be known. Its good we know whether something is a stake or a masternode reward. But if I have an address book, it should say "From Nick Saporano" if by some chance he sends me some divi.

**Comment by 99darwin** [comment]
The current network doesn't have 'From' addresses (neither does Bitcoin) but an issue has been triaged and the post-fork network will include this feature.
