### ISSUE TITLE
Wallet needs  a mini mode

### ISSUE THREAD

**Issue by hirscr** [DiviProject/Divi#94]
The wallet needs a mini mode. Just shows balance, some symbols for its state/mode, and some small messaging for incoming stakes/rewards/ or transfers. Most of the time I donned to see a list of transactions. I just want to know:

Current balance
If I am staking or not
If the masternodes are working or not
If my wallet is locked
If I have peers or not, maybe how many
When incoming Divi happens.

**Comment by cgruber** [comment]
Did you mean by "when something happens" just a marker that there is unseen activity? 

Other than that marker, most activity should just go through OS level notifications, and clicking on the notification should bring you out of mini mode.

**Comment by hirscr** [comment]
No, not unseen activity.  For example, when Telegram gives me a notification, it comes through the amc OS as a little window that goes away quickly, I can do a quick reply there if I want.

the divi wallet could generate a notification through the OS that a stake came in. It could also notify if network is lost, staking stops, I hit a new goal on balance (like having enough for the next masternode tier), etc. so a mini wallet, that utilizes the OS notification system.

**Comment by 99darwin** [comment]
Moved to the correct repo
