### ISSUE TITLE
Divi Desktop: Remove minimise or exit prompt on macOS

### ISSUE THREAD

**Issue by brindy** [DiviProject/Divi#96]
When pressing the red close icon in the window's toolbar, this means "close window" there's no need to ask "exit or minimise" because Mac users already know what this means because that's how every other app works.

<img width="212" alt="screenshot 2019-01-18 at 10 51 13" src="https://user-images.githubusercontent.com/81197/51382617-21f9f700-1b0f-11e9-824e-d2f289c5396e.png">

Minimise is especially confusing because the middle orange button on the toolbar means minimise, but rather than just closing the window this minimises to the dock, which is the macOS standard.

To exit you would normally use Cmd+Q or select it from the menu, but the current menu just has some pointless items in it:

<img width="282" alt="screenshot 2019-01-18 at 10 55 44" src="https://user-images.githubusercontent.com/81197/51382781-9e8cd580-1b0f-11e9-8058-ac116982c2bb.png">

All this menu really needs is the standard Quit menu item. Users will know this means shutdown the app completely because that's how every other app works.

Note, if you have unlocked your wallet for staking then it might make sense to ask the user if they meant to do this when they choose to quit the app.

**Comment by 99darwin** [comment]
Moved to the correct repo
