### ISSUE TITLE
Divi Core 1.0.6 - Allocation & Funding Errors Masternode - Testnet

### ISSUE THREAD

**Issue by gingfinger** [DiviProject/Divi#98]
On the new Daemon Core 1.0.6 when allocating funds for the Masternode. The transaction that goes to the account for the masternode is coming in short of full funds due to the tx fee being deducted. A copper MN only receives 99999.9 divi into the account and the 0.1 divi fee is deducted, leaving the account with not enough funds for the masternode.

When calling the fundmasternode command, and old error that we used to get in very early core editions has resurfaced. After calling fundmasternode command the "couldn't verify transaction" error is appearing

<img width="905" alt="Screenshot 2019-04-16 at 06 45 35" src="https://user-images.githubusercontent.com/39313339/56184992-00c47c00-6014-11e9-832c-39438ab7670f.png">

**Comment by gingfinger** [comment]
UPDATE: I have been able to bypass the allocation error by creating my own transaction to ensure that exactly 100k went into the account. With the account correctly allocated, the couldn't verify transaction error then disappears. So the overall error is caused by the initial allocation being short for the masternode tier. The second error is a result of the first

**Comment by 7h3v01c3** [comment]
If you tried with 100010 (100000 X1.0001=100010)

Will it work :)

**Comment by 99darwin** [comment]
Does the issue persist in https://github.com/Divicoin/Divi/commit/46f1d1f6959adbb4570a01a00f1be643db5f3133 ?

**Comment by gingfinger** [comment]
Issue is in 1.0.6b .. 1.0.6, allocation and funding was disabled. In 1.0.6b they are enabled but with the errors above

**Comment by 99darwin** [comment]
fixed in 1.0.7b
