### ISSUE TITLE
Divi Core 1.0.6 Masternode.conf creation -testnet

### ISSUE THREAD

**Issue by gingfinger** [DiviProject/Divi#99]
The core when launched does not create a masternode.conf file. If one is manually created and placed in the testnet3 folder, it doesn't utilise it when calling a start to a Masternode. Where should it be creating one in this new generation build. From what I can see it isn't creating one and isn't looking to use one from the usual location

**Comment by gingfinger** [comment]
Not sure if this info helps with diagnosis, but the divid.cpp from the current 1.0.4 vs the posv3 (1.0.6b) are different to the extent that the masternodeconfig.h is not being included in the new build:

This is the 1.0.4 divid.cpp:
![photo1](https://user-images.githubusercontent.com/39313339/56438244-22ef2000-62da-11e9-9c40-619d82d62f4f.jpg)


And this the 1.0.6 (posv3)
![photo2](https://user-images.githubusercontent.com/39313339/56438257-300c0f00-62da-11e9-92d9-a130c8583d1a.jpg)


I have also noted that upon using the fundmasternode command, a file of the same name as the masternode is then automatically created in the bin folder where divid is (i.e. 1.0.6/bin) .. when you open that file, it contains the output from fundmasternode of that particular MN, but is missing it's alias :
![MNfile](https://user-images.githubusercontent.com/39313339/56438412-c8a28f00-62da-11e9-8572-5a84b5e8d9bc.JPG)
![MNfileedit](https://user-images.githubusercontent.com/39313339/56438417-cb9d7f80-62da-11e9-92e4-1c8e48ba3835.JPG)

Is the creation of that new file in some way a replacement for a masternode.conf file? With the masternode info then being stored in the bin folder with specific files relating to each masternode an their associated configs? Which ever way they are supposed to link up, somehow at present they are not doing it

**Comment by 99darwin** [comment]
fixed in 1.0.7b
